### ISSUE TITLE
could you add more examples on how to send the transactions?

### ISSUE THREAD

**Issue by btfdip** [blockfrost/blockfrost-js#174]
Also, the example only show the get methods, while doesn't get involved with any post method.

**Comment by vladimirvolek** [comment]
> Also, the example only show the methods, while doesn't get involved with any method.

Heya
It's already on the roadmap! Thank you!

**Comment by vladimirvolek** [comment]
In the meantime check this https://github.com/Emurgo/cardano-serialization-lib/blob/master/doc/getting-started/generating-transactions.md

**Comment by slowbackspace** [comment]
Hi @akshitv1 and @btfdip! We've just merged an example on how to build a simple transaction and push it to the blockchain. I hope it will be useful for you!

https://github.com/blockfrost/blockfrost-js/tree/master/examples/simple-transaction

**Comment by akshitv1** [comment]
Hi @slowbackspace Is it not safe to use this for transactions on mainnet ? Why is that, i wanted to do the same, is there any other way.. Open for any advice or suggestions...

**Comment by akshitv1** [comment]
> 

Okay ! Yes thanks for the heads up !

**Comment by akshitv1** [comment]
Oh okay thanks that is exactly what i wanted to do now. 
So do i just push utxo's from different address, into this const utxo ?
https://github.com/blockfrost/blockfrost-js/blob/master/examples/simple-transaction/src/index.ts#L45
Hehe this sounds like a newb question even to me. But then this is like the last step to use blockfrost hehe
Thanks in advance for answering..

**Comment by slowbackspace** [comment]
You would also need to add witnesses for utxos from those other addresses (they are used for signing the tx).
Example adds only one witness, which is created with a private key associated with the address from which we take the utxo (`utxoKey`). 
So you would need to derive such key per each address and create necessary witnesses or slightly easier way is to use account private key (`accountKey`) as signing key to create only one witness that will cover all addresses (I assume they belong to the same account).

Signing key is returned from https://github.com/blockfrost/blockfrost-js/blob/master/examples/simple-transaction/src/helpers/key.ts#L45

Signing the tx is done in
https://github.com/blockfrost/blockfrost-js/blob/master/examples/simple-transaction/src/helpers/signTransaction.ts

**Comment by akshitv1** [comment]
Thanks ill try this today.

**Comment by akshitv1** [comment]
Hi @slowbackspace , i pushed all the utxo object from various addresses into the utxo object over here (https://github.com/blockfrost/blockfrost-js/blob/master/examples/simple-transaction/src/index.ts#L45),  by simple running a for loop over all the associated addresses and getting their utxos.

And i changed this return statement over here in key.js 
https://github.com/blockfrost/blockfrost-js/blob/master/examples/simple-transaction/src/helpers/key.ts#L45
to this :     return { signKey: accountKey.to_raw_key(), address: address };

But i can see the error that you mentioned, i guess its probably the witness validation error which might have come due to the accountKey. 

transaction submit error ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (MissingVKeyWitnessesUTXOW (WitHashes (fromList [KeyHash \"some hash here\"]))))])"
errr here : { BlockfrostServerError: "transaction submit error ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (MissingVKeyWitnessesUTXOW (WitHashes (fromList [KeyHash \"some hash here\"]))))])"

Can you pls point out the potential issue, also thanks for being so kind and replying so far.

**Comment by slowbackspace** [comment]
@akshitv1 Are you sure that all addresses belong to the same account for which you derive `accountKey`? You might want to ask for help on https://cardano.stackexchange.com as this is not related to Blockfrost, transaction was rejected by the blockchain, we are just forwarding the error.

**Comment by akshitv1** [comment]
Okay sure just wanted to confirm that i just took this accountKey over here https://github.com/blockfrost/blockfrost-js/blob/master/examples/simple-transaction/src/helpers/key.ts#L21
var accountKey = bipPrvKey
.derive(harden(1852)) // purpose
.derive(harden(1815)) // coin type
.derive(harden(accountIndex));
        
and just returned it like this: return { signKey: accountKey.to_raw_key(), address: address };

I am not sure if this is the accountKey that we are talking about here

**Comment by akshitv1** [comment]
Okay sure just wanted to confirm that i just took this accountKey over here https://github.com/blockfrost/blockfrost-js/blob/master/examples/simple-transaction/src/helpers/key.ts#L21
var accountKey = bipPrvKey
.derive(harden(1852)) // purpose
.derive(harden(1815)) // coin type
.derive(harden(accountIndex));

and just returned it like this: return { signKey: accountKey.to_raw_key(), address: address };

I am not sure if this is the accountKey that we are talking about here @slowbackspace 
I guess this might be the private key of account 0.
Were u talking about rootKey maybe, which is defined here(https://github.com/blockfrost/blockfrost-js/blob/master/examples/simple-transaction/src/helpers/key.ts#L53)

**Comment by akshitv1** [comment]
Hi @slowbackspace it is working when i use sign key of the particular address, 
I wanted to know if you have faced such an issue before : 
When i run this example from one place it works fine, but when i use it from the same directory but from a different file (lets say i run it from inside a node server) , it returns an empty Uint8Array(0) [] over here: transaction.to_bytes() (https://github.com/blockfrost/blockfrost-js/blob/master/examples/simple-transaction/src/index.ts#L88) 
Can this be some issue with wasm memory buffer maybe ?
